[package]
name = "cli-timer"
version = "0.1.0"
authors = ["ProgDroid"]
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4.1", features = ["derive"] }
crossterm = "0.25.0"
rand = "0.8"
rodio = "0.16"
tui = "0.19.0"
