on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Create ${{ matrix.config.os }} release
    if: github.repository_owner == 'progdroid'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: 'Windows', target: 'x86_64-pc-windows-gnu' }
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Compile and Release
        id: compile
        uses: rust-build/rust-build.action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.config.target }}
          ARCHIVE_TYPES: tar.gz
          UPLOAD_MODE: none
      - name: Get Crate Version
        id: crate-version
        uses: colathro/crate-version@1.0.0
        with:
          file: "./Cargo.toml"
      - name: Push Tag
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ format('v{0}', steps.crate-version.outputs.version) }}
          prerelease: false
          files: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
